### PR TITLE
Lumen Rest API

### PR DESCRIPTION
**Pull request by burrelle**

### CODE REVIEW

**Comment by agnelvishal** [comment]
Could you modify the query to return only `item_content,item_title,item_date, item_url,total,image,likes,shares,pa` instead of all.

**Comment by burrelle** [comment]
Updated

**Comment by agnelvishal** [comment]
/feeds returns data but /feeds/between?startDate={2018-01-29}&endDate={2018-10-29} or /feeds/between?startDate="2018-01-29"&endDate="2018-10-29" returns null. Why so?

**Comment by burrelle** [comment]
`/feeds/between?startDate=2018-04-22&endDate=2018-04-28`

**Comment by agnelvishal** [comment]
Thanks. One more thing. "ORDER BY total desc" needs to be added to the query

**Comment by burrelle** [comment]
`->orderBy('total', 'desc')`

**Pull request merged**
